name: Test, Build, Publish
on:
  push:
    paths-ignore: 
      - '**.md'
      - 'docs/**'
      - '**.txt'
  release:
    types: [published]

jobs:
  common:
    uses: interlinkai/Workflows/.github/workflows/dotnet-fw-build-publish.yaml@main
    with:
      solution_name: InterlinkAi.Print.DymoApp.sln
      project_name: InterlinkAi.Print.DymoApp.csproj
      run_tests: false
    secrets: inherit 
