name: Test, Build, Publish
on:
  push:
    paths-ignore: 
      - '**.md'
      - 'docs/**'
      - '**.txt'
  release:
    types: [published]

jobs:
  common:
    uses: interlinkai/Workflows/.github/workflows/dotnet-core-build-publish.yaml@main
    secrets: inherit 
